### ISSUE TITLE
There was an error deploying locally,

### ISSUE THREAD

**Issue by tuohao1125** [cyavu/AlbionCraftCalculator#2]
There was an error deploying locally,
I have correctly imported dump.sql
and the database is being used.

![image](https://user-images.githubusercontent.com/70328358/220620944-6af52d9b-56db-4323-86f0-ba0934c78fcc.png)

**Comment by cyavu** [comment]
> There was an error deploying locally, I have correctly imported dump.sql and the database is being used.
> 
> ![image](https://user-images.githubusercontent.com/70328358/220620944-6af52d9b-56db-4323-86f0-ba0934c78fcc.png)

Install php-curl and try again. I’ll update the documentation once this works for you.
